# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: laballea <laballea@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/10/06 08:02:24 by laballea          #+#    #+#              #
#    Updated: 2020/10/06 08:58:01 by laballea         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = clang++

CFLAGS = -Wall -Wextra -Werror

FT = main.cpp Zombie.cpp ZombieEvent.cpp

NAME = zombie

INCLUDE = ZombieEvent.hpp

all:
	${CC} ${CFLAGS} ${FT} -I ${INCLUDE} -o ${NAME}

fclean:
		rm -rf ${NAME}

re: fclean all

.PHONY : all fclean re